apiVersion: v1
kind: Service
metadata:
  name: vault-api-service
  namespace: vault
  labels:
    app: vault-api
spec:
  type: ClusterIP
  selector:
    app: vault-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
